-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| Select fields to build up a top-level mutation. The request can be sent with
functions from `Graphqelm.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootMutation
selection constructor =
    Object.selection constructor


type alias CreateDatasetRequiredArguments =
    { dataset : Api.InputObject.CreateDatasetInput }


createDataset : CreateDatasetRequiredArguments -> SelectionSet decodesTo Api.Object.Dataset -> Field (Maybe decodesTo) RootMutation
createDataset requiredArgs object =
    Object.selectionField "createDataset" [ Argument.required "dataset" requiredArgs.dataset Api.InputObject.encodeCreateDatasetInput ] object (identity >> Decode.nullable)


type alias DeleteDatasetRequiredArguments =
    { name : String, owner : String }


deleteDataset : DeleteDatasetRequiredArguments -> SelectionSet decodesTo Api.Object.Dataset -> Field (Maybe decodesTo) RootMutation
deleteDataset requiredArgs object =
    Object.selectionField "deleteDataset" [ Argument.required "name" requiredArgs.name Encode.string, Argument.required "owner" requiredArgs.owner Encode.string ] object (identity >> Decode.nullable)


deleteViewer : SelectionSet decodesTo Api.Object.User -> Field (Maybe decodesTo) RootMutation
deleteViewer object =
    Object.selectionField "deleteViewer" [] object (identity >> Decode.nullable)


type alias LoginRequiredArguments =
    { password : String, username : String }


login : LoginRequiredArguments -> SelectionSet decodesTo Api.Object.Session -> Field (Maybe decodesTo) RootMutation
login requiredArgs object =
    Object.selectionField "login" [ Argument.required "password" requiredArgs.password Encode.string, Argument.required "username" requiredArgs.username Encode.string ] object (identity >> Decode.nullable)


type alias RegisterRequiredArguments =
    { user : Api.InputObject.RegisterUserInput }


register : RegisterRequiredArguments -> SelectionSet decodesTo Api.Object.Session -> Field (Maybe decodesTo) RootMutation
register requiredArgs object =
    Object.selectionField "register" [ Argument.required "user" requiredArgs.user Api.InputObject.encodeRegisterUserInput ] object (identity >> Decode.nullable)


type alias UpdateDatasetRequiredArguments =
    { dataset : Api.InputObject.UpdateDatasetInput, name : String, owner : String }


updateDataset : UpdateDatasetRequiredArguments -> SelectionSet decodesTo Api.Object.Dataset -> Field (Maybe decodesTo) RootMutation
updateDataset requiredArgs object =
    Object.selectionField "updateDataset" [ Argument.required "dataset" requiredArgs.dataset Api.InputObject.encodeUpdateDatasetInput, Argument.required "name" requiredArgs.name Encode.string, Argument.required "owner" requiredArgs.owner Encode.string ] object (identity >> Decode.nullable)


type alias UpdateViewerRequiredArguments =
    { user : Api.InputObject.UpdateUserInput }


updateViewer : UpdateViewerRequiredArguments -> SelectionSet decodesTo Api.Object.User -> Field (Maybe decodesTo) RootMutation
updateViewer requiredArgs object =
    Object.selectionField "updateViewer" [ Argument.required "user" requiredArgs.user Api.InputObject.encodeUpdateUserInput ] object (identity >> Decode.nullable)
