-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type DataType
    = DataType


type DatapointConnection
    = DatapointConnection


type DatapointEdge
    = DatapointEdge


type Dataset
    = Dataset


type DatasetConnection
    = DatasetConnection


type DatasetEdge
    = DatasetEdge


type DatasetExportPayload
    = DatasetExportPayload


type Image
    = Image


type ImageBoundingBox
    = ImageBoundingBox


type ImageBoundingBoxDefinition
    = ImageBoundingBoxDefinition


type ImageClass
    = ImageClass


type ImageClassDefinition
    = ImageClassDefinition


type LabelType
    = LabelType


type Organization
    = Organization


type PageInfo
    = PageInfo


type Session
    = Session


type Text
    = Text


type User
    = User


type Video
    = Video
