-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type DataType
    = DataType


type Dataset
    = Dataset


type Image
    = Image


type ImageBoundingBox
    = ImageBoundingBox


type ImageBoundingBoxDefinition
    = ImageBoundingBoxDefinition


type ImageClass
    = ImageClass


type ImageClassDefinition
    = ImageClassDefinition


type LabelType
    = LabelType


type Organization
    = Organization


type Session
    = Session


type Text
    = Text


type User
    = User


type Video
    = Video
