-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Union exposing (..)


type Datapoint
    = Datapoint


type Label
    = Label


type LabelDefinition
    = LabelDefinition
