-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.DataType exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.DataType
selection constructor =
    Object.selection constructor


labelTypes : SelectionSet decodesTo Api.Object.LabelType -> Field (List decodesTo) Api.Object.DataType
labelTypes object =
    Object.selectionField "labelTypes" [] object (identity >> Decode.list)


name : Field String Api.Object.DataType
name =
    Object.fieldDecoder "name" [] Decode.string
