-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Image exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Image
selection constructor =
    Object.selection constructor


caption : Field (Maybe String) Api.Object.Image
caption =
    Object.fieldDecoder "caption" [] (Decode.string |> Decode.nullable)


compressionFormat : Field String Api.Object.Image
compressionFormat =
    Object.fieldDecoder "compressionFormat" [] Decode.string


depth : Field Int Api.Object.Image
depth =
    Object.fieldDecoder "depth" [] Decode.int


filesize : Field Int Api.Object.Image
filesize =
    Object.fieldDecoder "filesize" [] Decode.int


height : Field Int Api.Object.Image
height =
    Object.fieldDecoder "height" [] Decode.int


id : Field Api.Scalar.Id Api.Object.Image
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id)


labels : SelectionSet decodesTo Api.Union.Label -> Field (List decodesTo) Api.Object.Image
labels object =
    Object.selectionField "labels" [] object (identity >> Decode.list)


storagePath : Field String Api.Object.Image
storagePath =
    Object.fieldDecoder "storagePath" [] Decode.string


width : Field Int Api.Object.Image
width =
    Object.fieldDecoder "width" [] Decode.int
