-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Video exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Video
selection constructor =
    Object.selection constructor


caption : Field (Maybe String) Api.Object.Video
caption =
    Object.fieldDecoder "caption" [] (Decode.string |> Decode.nullable)


compressionFormat : Field (Maybe String) Api.Object.Video
compressionFormat =
    Object.fieldDecoder "compressionFormat" [] (Decode.string |> Decode.nullable)


depth : Field (Maybe Int) Api.Object.Video
depth =
    Object.fieldDecoder "depth" [] (Decode.int |> Decode.nullable)


duration : Field (Maybe Int) Api.Object.Video
duration =
    Object.fieldDecoder "duration" [] (Decode.int |> Decode.nullable)


height : Field (Maybe Int) Api.Object.Video
height =
    Object.fieldDecoder "height" [] (Decode.int |> Decode.nullable)


id : Field Api.Scalar.Id Api.Object.Video
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id)


storagePath : Field (Maybe String) Api.Object.Video
storagePath =
    Object.fieldDecoder "storagePath" [] (Decode.string |> Decode.nullable)


width : Field (Maybe Int) Api.Object.Video
width =
    Object.fieldDecoder "width" [] (Decode.int |> Decode.nullable)
