-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Union.Datapoint exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (FragmentSelectionSet(FragmentSelectionSet), SelectionSet(SelectionSet))
import Json.Decode as Decode


selection : (Maybe typeSpecific -> constructor) -> List (FragmentSelectionSet typeSpecific Api.Union.Datapoint) -> SelectionSet constructor Api.Union.Datapoint
selection constructor typeSpecificDecoders =
    Object.unionSelection typeSpecificDecoders constructor


onImage : SelectionSet decodesTo Api.Object.Image -> FragmentSelectionSet decodesTo Api.Union.Datapoint
onImage (SelectionSet fields decoder) =
    FragmentSelectionSet "Image" fields decoder


onText : SelectionSet decodesTo Api.Object.Text -> FragmentSelectionSet decodesTo Api.Union.Datapoint
onText (SelectionSet fields decoder) =
    FragmentSelectionSet "Text" fields decoder


onVideo : SelectionSet decodesTo Api.Object.Video -> FragmentSelectionSet decodesTo Api.Union.Datapoint
onVideo (SelectionSet fields decoder) =
    FragmentSelectionSet "Video" fields decoder
