-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Union.LabelDefinition exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (FragmentSelectionSet(FragmentSelectionSet), SelectionSet(SelectionSet))
import Json.Decode as Decode


selection : (Maybe typeSpecific -> constructor) -> List (FragmentSelectionSet typeSpecific Api.Union.LabelDefinition) -> SelectionSet constructor Api.Union.LabelDefinition
selection constructor typeSpecificDecoders =
    Object.unionSelection typeSpecificDecoders constructor


onImageClassDefinition : SelectionSet decodesTo Api.Object.ImageClassDefinition -> FragmentSelectionSet decodesTo Api.Union.LabelDefinition
onImageClassDefinition (SelectionSet fields decoder) =
    FragmentSelectionSet "ImageClassDefinition" fields decoder


onImageBoundingBoxDefinition : SelectionSet decodesTo Api.Object.ImageBoundingBoxDefinition -> FragmentSelectionSet decodesTo Api.Union.LabelDefinition
onImageBoundingBoxDefinition (SelectionSet fields decoder) =
    FragmentSelectionSet "ImageBoundingBoxDefinition" fields decoder
