-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Union.Label exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (FragmentSelectionSet(FragmentSelectionSet), SelectionSet(SelectionSet))
import Json.Decode as Decode


selection : (Maybe typeSpecific -> constructor) -> List (FragmentSelectionSet typeSpecific Api.Union.Label) -> SelectionSet constructor Api.Union.Label
selection constructor typeSpecificDecoders =
    Object.unionSelection typeSpecificDecoders constructor


onImageClass : SelectionSet decodesTo Api.Object.ImageClass -> FragmentSelectionSet decodesTo Api.Union.Label
onImageClass (SelectionSet fields decoder) =
    FragmentSelectionSet "ImageClass" fields decoder


onImageBoundingBox : SelectionSet decodesTo Api.Object.ImageBoundingBox -> FragmentSelectionSet decodesTo Api.Union.Label
onImageBoundingBox (SelectionSet fields decoder) =
    FragmentSelectionSet "ImageBoundingBox" fields decoder
